service: frame-extractor
runtime: custom
env: flex

# [START gae_flex_pubsub_yaml]
env_variables:
  PUBSUB_TOPIC: topic_extractor
  # This token is used to verify that requests originate from your
  # application. It can be any sufficiently random string.
  PUBSUB_VERIFICATION_TOKEN: ok123456
# [END gae_flex_pubsub_yaml]
